kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: CI_PROJECT_NAME
  namespace: KUBE_NAMESPACE
  labels:
    app: CI_PROJECT_NAME
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG    
spec:
  scaleTargetRef:
    kind: Deployment
    name: CI_PROJECT_NAME
    apiVersion: apps/v1
  minReplicas: POD_REPLICA_MIN #1
  maxReplicas: POD_REPLICA_MAX #3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: SCALING_BY_CPU_PERC #90